service: portfolio-backend

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    PYTHON_SERVICE_URL: ${env:PYTHON_SERVICE_URL}

functions:
  api:
    handler: dist/index.handler
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
    environment:
      NODE_ENV: ${self:provider.stage}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 4000
    host: 0.0.0.0

package:
  patterns:
    - '!node_modules/**'
    - '!src/**'
    - '!tests/**'
    - '!*.md'
    - 'dist/**'
